urls:
  - https://shopee.com.br/24-Pe%C3%A7as-Suporte-A-V%C3%A1cuo-Anti-Celulite-Acupuntura-Massagem-Com-Ventosa-i.581491760.15538395933
  - https://shopee.com.br/Amplificador-De-Pot%C3%AAncia-De-%C3%81udio-speaker-amp-AK380-800W-Para-Carro-CD-MP3-Telefone-Amplificador-Bluetooth-Carro-Karaok%C3%AA-Home-Theater-i.581491760.16604914064
  - https://shopee.com.br/Luvas-De-Goleiro-De-Futebol-Adidas-Americano-Respir%C3%A1vel-i.581491760.10190871203
  - https://shopee.com.br/-Em-estoque-Luva-De-Goleiro-Falcon-Flex%C3%ADvel-E-Confort%C3%A1vel-Antiderrapante-Luvas-Profissional-Luvas-De-Treinamento-Americano-L%C3%A1tex-Grosso-i.581491760.14471773624
  - https://shopee.com.br/-in-stock-100-Pe%C3%A7as-Terminais-El%C3%A9tricos-Ilh%C3%B3s-Tubular-Simples-Pr%C3%A9-Isolado-2-5mm-VE-i.581491760.8897653002
  - https://shopee.com.br/m-VE-i.724659268.13992870026
